<?php

namespace Gatomlo\UserBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
  public function getUserListWithoutOneUser($user)
  {
    $qb = $this->createQueryBuilder('o');
    $qb->where('o != :o')
       ->setParameter(':o',$user);

       return $qb->getQuery()->getResult();
  }
}
