<?php

namespace Gatomlo\ProjectManagerBundle\Repository;

/**
 * IntervenantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IntervenantRepository extends \Doctrine\ORM\EntityRepository
{
  public function getProjectsArchivedOrNotFromIntervenant($intervenant,$archived)
  {
    return $this->createQueryBuilder('e')
    ->join('e.project', 'p')
    ->where('e.people = :intervenant')
    ->setParameter(':intervenant',$intervenant)
    ->andwhere('p.archived = :archived')
    ->setParameter(':archived',$archived)
    ->getQuery()
    ->getResult();
  }
}
