<?php

namespace Gatomlo\ProjectManagerBundle\Repository;

/**
 * ReportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReportRepository extends \Doctrine\ORM\EntityRepository
{
  public function getReportsFromOwner($user)
  {
    $qb = $this->createQueryBuilder('e');
    $qb->join('e.owner','o')
       ->andWhere('o = :o')
       ->setParameter(':o',$user);

       return $qb->getQuery()->getResult();
  }

}
