
#main
gatomlo_project_manager_homepage:
    path:     /
    defaults: { _controller: GatomloProjectManagerBundle:Default:index }

gatomlo_project_manager_config:
    path:     /configuration
    defaults: { _controller: GatomloProjectManagerBundle:Default:configuration }


#projets
gatomlo_project_manager_all_projects:
    path:      /projects/all/{archived}
    defaults:
      _controller: GatomloProjectManagerBundle:Project:all
      archived: FALSE
    requirements:
        archived: 0|1

gatomlo_project_manager_projects_json:
    path:      /projects/json
    defaults: { _controller: GatomloProjectManagerBundle:Project:jsonProjectsList }


gatomlo_project_manager_one_project:
    path:      /projects/{id}
    defaults: { _controller: GatomloProjectManagerBundle:Project:view }
    requirements:
        id: \d+

gatomlo_project_manager_add_project:
    path:      /projects/add
    defaults: { _controller: GatomloProjectManagerBundle:Project:add }

gatomlo_project_manager_edit_project:
    path:      /projects/edit/{id}
    defaults: { _controller: GatomloProjectManagerBundle:Project:edit }
    requirements:
        id: \d+

gatomlo_project_manager_delete_project:
    path:      /projects/delete/{id}
    defaults: { _controller: GatomloProjectManagerBundle:Project:delete }
    requirements:
        id: \d+

gatomlo_project_manager_archived_project:
    path:      /projects/archived/{id}
    defaults: { _controller: GatomloProjectManagerBundle:Project:archived }
    requirements:
        id: \d+

gatomlo_project_manager_add_project_to_parent:
    path:      /projects/add_to_parent/{idChild}/{idParent}
    defaults: { _controller: GatomloProjectManagerBundle:Project:addParent }
    requirements:
        idChild: \d+
        idParent: \d+

gatomlo_project_manager_remove_parent_from_project:
    path:      /projects/remove_a_parent/{idParent}
    defaults: { _controller: GatomloProjectManagerBundle:Project:removeParent }
    requirements:
        idParent: \d

#peoples
gatomlo_project_manager_all_peoples:
    path:      /peoples/all
    defaults: { _controller: GatomloProjectManagerBundle:People:all }

gatomlo_project_manager_one_people:
    path:      /peoples/{id}
    defaults: { _controller: GatomloProjectManagerBundle:People:view }
    requirements:
        id: \d+

gatomlo_project_manager_add_people:
    path:      /peoples/add
    defaults: { _controller: GatomloProjectManagerBundle:People:add }

gatomlo_project_manager_edit_people:
    path:      /peoples/edit/{id}
    defaults: { _controller: GatomloProjectManagerBundle:People:edit }
    requirements:
        id: \d+

gatomlo_project_manager_delete_people:
    path:      /peoples/delete/{id}
    defaults: { _controller: GatomloProjectManagerBundle:People:delete }
    requirements:
        id: \d+

#intervenants
gatomlo_project_manager_all_intervenants_from_a_project:
    path:      /intervenants/all/project/{projectId}
    defaults: { _controller: GatomloProjectManagerBundle:Intervenant:allForProject }
    requirements:
        projectId: \d+

gatomlo_project_manager_all_intervenants_from_a_people:
    path:      /intervenants/all/people/{peopleId}/{isArchived}
    defaults: { _controller: GatomloProjectManagerBundle:Intervenant:allForPeople }
    requirements:
        peopleId: \d+
        archived: 0|1

gatomlo_project_manager_add_Intervenant:
    path:      /intervenants/add/{from}/{id}
    defaults: { _controller: GatomloProjectManagerBundle:Intervenant:add }
    requirements:
        id: \d+
        from: project|people


gatomlo_project_manager_edit_intervenant:
    path:      /intervenants/edit/{id}/{from}
    defaults: { _controller: GatomloProjectManagerBundle:Intervenant:edit }
    requirements:
        id: \d+
        from: project|people

gatomlo_project_manager_delete_intervenant:
    path:      /intervenants/delete/{id}/{from}
    defaults: { _controller: GatomloProjectManagerBundle:Intervenant:delete }
    requirements:
        id: \d+
        from: project|people

gatomlo_project_manager_deadline_projects_json:
    path:      /projects/json/deadline/all
    defaults: { _controller: GatomloProjectManagerBundle:Project:jsonDeadlineProjectsList }


#events
gatomlo_project_manager_all_events:
    path:      /events/all
    defaults: { _controller: GatomloProjectManagerBundle:Event:all }

gatomlo_project_manager_all_events_from_a_project:
    path:      /events/all/{projectId}
    defaults: { _controller: GatomloProjectManagerBundle:Event:allFor }
    requirements:
        projectId: \d+

gatomlo_project_manager_one_event:
    path:      /events/{id}
    defaults: { _controller: GatomloProjectManagerBundle:Event:view }
    requirements:
        id: \d+

gatomlo_project_manager_add_event:
    path:      /events/add/
    defaults: { _controller: GatomloProjectManagerBundle:Event:add }

gatomlo_project_manager_add_event_from_project:
    path:      /events/add/{projectId}
    defaults: { _controller: GatomloProjectManagerBundle:Event:add }
    requirements:
        id: \d+

gatomlo_project_manager_edit_event:
    path:      /events/edit/{id}
    defaults: { _controller: GatomloProjectManagerBundle:Event:edit }
    requirements:
        id: \d+

gatomlo_project_manager_delete_event:
    path:      /events/delete/{id}/{from}
    defaults: { _controller: GatomloProjectManagerBundle:Event:delete }
    requirements:
        id: \d+
        from: project|events

#tags
gatomlo_project_manager_tags_json:
    path:      /tags/
    defaults: { _controller: GatomloProjectManagerBundle:Tags:jsonTagsList }

#tasks
gatomlo_project_manager_all_open_tasks:
    path:      /tasks/all/open/
    defaults: { _controller: GatomloProjectManagerBundle:Task:allOpenTask }


gatomlo_project_manager_all_closed_tasks:
    path:      /tasks/all/closed/
    defaults: { _controller: GatomloProjectManagerBundle:Task:allClosedTask }



gatomlo_project_manager_all_tasks_plannificator:
    path:      /tasks/plannificator/all
    defaults: { _controller: GatomloProjectManagerBundle:Task:plannificator }

gatomlo_project_manager_all_tasks_from_a_project:
    path:      /tasks/all/{projectId}
    defaults: { _controller: GatomloProjectManagerBundle:Task:allFor }
    requirements:
        projectId: \d+

gatomlo_project_manager_add_task:
    path:      /tasks/add/
    defaults: { _controller: GatomloProjectManagerBundle:Task:add }

gatomlo_project_manager_add_task_from_project:
    path:      /tasks/add/{projectId}
    defaults: { _controller: GatomloProjectManagerBundle:Task:add }
    requirements:
        id: \d+

gatomlo_project_manager_edit_task:
    path:      /tasks/edit/{id}
    defaults: { _controller: GatomloProjectManagerBundle:Task:edit }
    requirements:
        id: \d+
gatomlo_project_manager_change_planiffied_date_task:
    path:      /tasks/plannified/
    defaults: { _controller: GatomloProjectManagerBundle:Task:plannified }

gatomlo_project_manager_close_task:
    path:      /tasks/close/{id}/{from}
    defaults: { _controller: GatomloProjectManagerBundle:Task:close }
    requirements:
        id: \d+
        from: project|tasks|index

gatomlo_project_manager_delete_task:
    path:      /tasks/delete/{id}/{from}
    defaults: { _controller: GatomloProjectManagerBundle:Task:delete }
    requirements:
        id: \d+
        from: project|tasks

gatomlo_project_manager_deadline_tasks_json:
    path:      /tasks/json/deadline/all
    defaults: { _controller: GatomloProjectManagerBundle:Task:jsonDeadlineTaksList }

gatomlo_project_manager_planned_tasks_json:
    path:      /tasks/json/planned/all
    defaults: { _controller: GatomloProjectManagerBundle:Task:jsonPlanTaksList }
