
#main
gatomlo_project_manager_homepage:
    path:     /
    defaults: { _controller: GatomloProjectManagerBundle:Default:index }

gatomlo_project_manager_config:
    path:     /configuration
    defaults: { _controller: GatomloProjectManagerBundle:Default:configuration }


#projets
gatomlo_project_manager_all_projects:
    path:      /projects/all/{archived}
    defaults:
      _controller: GatomloProjectManagerBundle:Project:all
      archived: FALSE
    requirements:
        archived: 0|1

gatomlo_project_manager_one_project:
    path:      /projects/{id}
    defaults: { _controller: GatomloProjectManagerBundle:Project:view }
    requirements:
        id: \d+

gatomlo_project_manager_add_project:
    path:      /projects/add
    defaults: { _controller: GatomloProjectManagerBundle:Project:add }

gatomlo_project_manager_edit_project:
    path:      /projects/edit/{id}
    defaults: { _controller: GatomloProjectManagerBundle:Project:edit }
    requirements:
        id: \d+

gatomlo_project_manager_delete_project:
    path:      /projects/delete/{id}
    defaults: { _controller: GatomloProjectManagerBundle:Project:delete }
    requirements:
        id: \d+

gatomlo_project_manager_archived_project:
    path:      /projects/archived/{id}
    defaults: { _controller: GatomloProjectManagerBundle:Project:archived }
    requirements:
        id: \d+


gatomlo_project_manager_add_project_to_parent:
    path:      /projects/add_to_parent/{idChild}/{idParent}
    defaults: { _controller: GatomloProjectManagerBundle:Project:addParent }
    requirements:
        idChild: \d+
        idParent: \d+


#peoples
gatomlo_project_manager_all_peoples:
    path:      /peoples/all
    defaults: { _controller: GatomloProjectManagerBundle:People:all }

gatomlo_project_manager_one_people:
    path:      /peoples/{id}
    defaults: { _controller: GatomloProjectManagerBundle:People:view }
    requirements:
        id: \d+

gatomlo_project_manager_add_people:
    path:      /peoples/add
    defaults: { _controller: GatomloProjectManagerBundle:People:add }

gatomlo_project_manager_edit_people:
    path:      /peoples/edit/{id}
    defaults: { _controller: GatomloProjectManagerBundle:People:edit }
    requirements:
        id: \d+

gatomlo_project_manager_delete_people:
    path:      /peoples/delete/{id}
    defaults: { _controller: GatomloProjectManagerBundle:People:delete }
    requirements:
        id: \d+

#events
gatomlo_project_manager_all_events:
    path:      /events/all
    defaults: { _controller: GatomloProjectManagerBundle:Event:all }

gatomlo_project_manager_all_events_from_a_project:
    path:      /events/all/{projectId}
    defaults: { _controller: GatomloProjectManagerBundle:Event:allFor }
    requirements:
        projectId: \d+

gatomlo_project_manager_one_event:
    path:      /events/{id}
    defaults: { _controller: GatomloProjectManagerBundle:Event:view }
    requirements:
        id: \d+

gatomlo_project_manager_add_event:
    path:      /events/add
    defaults: { _controller: GatomloProjectManagerBundle:Event:add }

gatomlo_project_manager_edit_event:
    path:      /events/edit/{id}
    defaults: { _controller: GatomloProjectManagerBundle:Event:edit }
    requirements:
        id: \d+

gatomlo_project_manager_delete_event:
    path:      /events/delete/{id}/{from}
    defaults: { _controller: GatomloProjectManagerBundle:Event:delete }
    requirements:
        id: \d+
        from: project|events

#tasks
gatomlo_project_manager_all_tasks:
    path:      /tasks/all
    defaults: { _controller: GatomloProjectManagerBundle:Task:all }

gatomlo_project_manager_one_task:
    path:      /tasks/{id}
    defaults: { _controller: GatomloProjectManagerBundle:Task:view }
    requirements:
          id: \d+

gatomlo_project_manager_add_task:
    path:      /tasks/add
    defaults: { _controller: GatomloProjectManagerBundle:Task:add }

gatomlo_project_manager_edit_task:
    path:      /tasks/edit/{id}
    defaults: { _controller: GatomloProjectManagerBundle:Task:edit }
    requirements:
        id: \d+

gatomlo_project_manager_delete_tasks:
    path:      /tasks/delete/{id}
    defaults: { _controller: GatomloProjectManagerBundle:Task:delete }
    requirements:
        id: \d+
