services:
#    gatomlo_project_manager.example:
#        class: Gatomlo\ProjectManagerBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
  twig.extension.text:
       class: Twig_Extensions_Extension_Text
       tags:
           - { name: twig.extension }
